### ISSUE TITLE
Add external service support for API endpoints

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#487] opened 2023-01-12 05:27 UTC
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Amila-Rukshan** [comment] 2023-01-18 06:15
duplicate of https://github.com/wso2/apk/issues/514

**Closed by Amila-Rukshan** 2023-01-18 06:15 UTC
Labels: component/adapter
