### ISSUE TITLE
[APK Management Server and Adapter] initiate and configure the Database connection

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/apk#84] opened 2022-10-31 04:57 UTC
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by VajiraPrabuddhaka** [comment] 2022-11-15 05:49
closing this as a duplicate of https://github.com/wso2/apk/issues/120

**Closed by VajiraPrabuddhaka** 2022-11-15 05:49 UTC
Labels: Type/New Feature
